#!/bin/bash

if [ "$1" == "all" ]; then
	node=""
else
	node=${1}
fi

cnt=0
cmd_string=""
for cmd in ${*}; do
	if [ "$cnt" == "0" ]; then
		cnt=`expr $cnt + 1`
		continue
	fi
	cmd_string="${cmd_string} ${cmd}"
done

for i in $(docker ps | grep mnta-env | grep "$node" | awk '{ print $1 }'); do
	echo "***************************************************************************"
       	echo -n "${i}: ";
       	docker exec $i /moneta/src/moneta-cli ${cmd_string};
	echo "***************************************************************************"
done
